// <auto-generated />
using System;
using FanPage.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FanPage.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191127182759_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FanPage.Models.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText");

                    b.Property<int?>("StoryID");

                    b.Property<string>("User");

                    b.HasKey("CommentID");

                    b.HasIndex("StoryID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("FanPage.Models.Story", b =>
                {
                    b.Property<int>("StoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("StoryText");

                    b.Property<string>("Title");

                    b.Property<int?>("UserId");

                    b.Property<string>("Writer");

                    b.HasKey("StoryID");

                    b.HasIndex("UserId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("FanPage.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FanPage.Models.Comment", b =>
                {
                    b.HasOne("FanPage.Models.Story")
                        .WithMany("Comments")
                        .HasForeignKey("StoryID");
                });

            modelBuilder.Entity("FanPage.Models.Story", b =>
                {
                    b.HasOne("FanPage.Models.User")
                        .WithMany("Stories")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
